### ISSUE TITLE
event for knob (qty)

### ISSUE THREAD

**Issue by LLIMEJI** [zircleUI/zircleUI#13]
Hi there.

I need to catch the event for knob (qty), then transfer the data to the back-end, but the documentation and tutorial do not say anything about it (only click, but it's works bad for mobile). Is this event described in zircle.ui or is it necessary to describe it yourself?

**Comment by tinchox5** [comment]
Hi Igor, here it is the  information about using knob: https://zircleui.github.io/docs/api/z-spot.html#z-spot-as-knob

Give me some hours and I will post here a basic example to catch the `qty` value .  Maybe the tutorial and documentations are not clear enough.

**Comment by tinchox5** [comment]
Igor, here I made an example using `z-spot` as a `knob`. I realized the documentation is not clear about how to handle the values when using prop `qty`. Sorry about that, I'll fix as soon as possible.

I hope this example helps you to understand how to handle this situation: 

https://codepen.io/zircle/pen/EeBXQO

**Comment by LLIMEJI** [comment]
Thanks, Juan. I think this is what I need
