### ISSUE TITLE
Stuck in creating an app according to documentation

### ISSUE THREAD

**Issue by Paperasse** [zircleUI/zircleUI#14]
I'm starting a project with zircle. I have followed up the steps in the "First steps" section. Created everything as described. Touched no other files. Get stuck on the import of the home view. Following error message: 

 ERROR  Failed to compile with 1 errors                                                                                            15:51:25
This dependency was not found:

* /views/home.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&

**Comment by tinchox5** [comment]
Hi Henk!
Thank you filling this issue. Are referring  to this link
https://zircleui.github.io/docs/tutorial/setup-files.html ?

It seems that the error is due to ‘home.vue’ is not found.  Please check if
the folder ‘views’ exists inside the ‘src’ folder.

**Comment by tinchox5** [comment]
I think there is a typo error: please change `import home from '/views/home'` for `import home from './views/home'`

**Comment by tinchox5** [comment]
Ok, if you couldn’t arrive to a solution I’ll work on this issue when arrive home

**Comment by tinchox5** [comment]
Henk, I confirm that the problem is that in the tutorial's documentation (first steps) the **`home.vue`** file  points to `/views/home` but has to  point to **`./views/home`**

Here is a code sandbox with the working solution. https://codesandbox.io/s/m7ky0r7oqp

Would you like to help me to correct this typo mistake by submitting a PR? 
(you can follow [this link](https://github.com/zircleUI/docs/edit/master/docs/tutorial/setup-files.md) to edit **line 42** the source code of this page )

**Comment by Paperasse** [comment]
Ok. I will try to edit docs and do a pr.


Henk Feijt

**Comment by tinchox5** [comment]
Thank you Henk for the PR

**Comment by Paperasse** [comment]
Will publish app soon on netfily.

**Comment by tinchox5** [comment]
Let me know when publish! I want to know what the community is doing with zircle!

**Comment by Paperasse** [comment]
An early prototype you'll finf at bmi-zircleui.netlify.com. Its is body mass index calculator. In Dutch language. Only skeleton for now.

**Comment by tinchox5** [comment]
Nice! Let me know when you finish it, I'm thinking in create some kind of community showcase to show what can be done with zircle.
