### ISSUE TITLE
Navigate to view in code.

### ISSUE THREAD

**Issue by Paperasse** [zircleUI/zircleUI#16]
It would be nice to go a view in code. Example: in a view the user enters data which is stored in de vuex store through an mutation. After that the app needs to navigate to another view. A "toView' function perhaps?

**Comment by tinchox5** [comment]
Do you mean programmatic navigation? I think this is a good feature to add. I'll work on that.
Thanks!!

**Comment by Paperasse** [comment]
Yes that is what I mean. Thanks.

**Comment by Paperasse** [comment]
The Vue router has such a function

**Comment by tinchox5** [comment]
@Paperasse I added a `$zircle`action called `toView()` to perform programmatic navigation. 🎉 Available on **zircle v.1.1.0**. You should update zircle to use it.

Pls check the documentation: 
https://zircleui.github.io/docs/api/z-spot.html#using-programmatic-navigation

**Comment by Paperasse** [comment]
Ok. Will update and use it. Will let you know if there something wrong. Thanks.
