### ISSUE TITLE
Routing (vue-router) not working with zircleui?

### ISSUE THREAD

**Issue by driekus77** [zircleUI/zircleUI#19]
**What issues can I inform?**
bug in documentation?

**How to inform?**
I'm new to zircleui and using the Vue ecosystem example as base for our new DTAP status monitoring webpage. Everything seems to be working fine! (Thanks for this lib!)
Only one thing I can't get working is using routing (vue-router) with zircleui. 

I'm configured it according to https://zircleui.github.io/docs/guide/using-vue-router.html#for-browser-or-code-sandboxes.

With config code:
`
   const routes = [
    {
        path: '/home', component: Home,
        children: [
            { path: '/production', component: Production },
            { path: '/acceptance', component: Acceptance },
            { path: '/test', component: Test },
            { path: '/development', component: Development }
        ]
    }
   ];

  const router = new VueRouter({
    hashbang: true,
    //abstract: true,
    history: true,
    //mode: 'html5',
    linkActiveClass: 'active',
    transitionOnLoad: true,
    root: '/',
    //routes: routes 
  })

   new Vue({
    el: '#app',
    router,
    store: store,
    components: {
        'production': Production,
        'acceptance': Acceptance,
        'test': Test,
        'development': Development,
        'home': Home,
        'resource': Resource
    },
    mounted() {
        this.$zircle.config({
            mode: 'full',
            style: {
                theme: 'green',
                mode: 'dark'
            },
            router: router
        });
        this.$zircle.setView('home');
    }
   })
`

Am I missing something?

Any help would be appreciated!

Kind regards,

Henry Roeland

**Comment by tinchox5** [comment]
Thank you for open this issue. I'll work on it ASAP

**Comment by tinchox5** [comment]
@driekus77 I run a setup of vue-router from scratch under the node environment and the following code seems to work fine:

``` App.vue
<template>
  <z-canvas :views="$options.components" />
</template>
<script>
// 1
import Vue from 'vue'
import Router from 'vue-router'
Vue.use(Router)

import Production from '/path-to-components/Production'
...
//
// 2
const router = new Router({})
//
export default {
  components: {
// 3
  production: Production,
 acceptance: Acceptance,
 test: Test,
 development: Development,
home: Home,
resource: Resource
//
  },
// 4
  router,
//
  mounted () {
    this.$zircle.config({
// 5
      router
//
    })
    this.$zircle.setView('home')
  }
}
</script>
```

The key points are: 
1. You need to import **Vue** and **Vue-router** into **App.vue**. Also, you need to import your views.
2. Start a vue-router object `const router = new Router({})`. There is not need to create `routes` since zircle handles them automatically based on the components. 
3. Reference your views under `components: {}`.
4. Put the router object inside you vue instance
5. Put the router onject inside the zircle config

I hope this explanation contributes to solve your problem!

**Comment by tinchox5** [comment]
Hi @driekus77,
I fully understand what you said regarding the use of the routes... I'm afraid there is an important limitation when you use a route and zircle together: right now always you enter a route the router redirects to the initial view (eg: home). 

Sorry about that, maybe it is useless for you using a router on this conditions. However, in the near future I could try to fix that by overriding the redirect action in case the user manually set a route.

**Comment by tinchox5** [comment]
I mean using a router with zircle is not possible in a conventional way right now because as zircle uses a kind of stalked views (the previous view is visible along with the current view). I have to find a solution to render the previous views as well, not only the current one. But I think it's possible to reach a solution.

**Comment by driekus77** [comment]
Hi @tinchox5,

I've managed to get a workarround by using the vue-router only. Together with:


```
   if (vm.$route.path != undefined && vm.$route.path.length > 1) {
            var viewName = '';
            if (vm.$route.path == '/production') {
                viewName = 'production';
            }
            else if (vm.$route.path == '/acceptance') {
                viewName = 'acceptance';
            }
            else if (vm.$route.path == '/test') {
                viewName = 'test';
            }
            else if (vm.$route.path == '/development') {
                viewName = 'development';
            }
            this.$zircle.setView(viewName);
        }
        else {
            this.$router.replace('/');
        }
```

And in the environment specific views in mounted I use:

`this.$router.replace('/production');`

You are right: The previous view is not there so only the routed view is visible. But I can navigate back to home so for me its fine.

Thanks again for you quick responses and help. 

Keep up to good work with is nice library!

Kind regards,

Henry Roeland

**Comment by driekus77** [comment]
My workarround does need events: 
When returning from a view (no idea???)
When (re)entering a view (mounted?)

This in order to replace the url properly.

Can you give me some advice?

Thanks

**Comment by driekus77** [comment]
Events like @click -> @enterView | @leaveView

Or hooks like mounted -> enter | beforeLeave

I know the Enter view can be done in existing mounted hook. But for the leave I cant think of something.

**Comment by phshy0607** [comment]
Hi, I have a problem with routing too.

I'm using **auth0** as my third party authentication service, after I did the login logic, the auth0 service will call a callback URL (in this scenario callback URL will be http://localhost:8080/callback).

I've been playing around with this beautiful library for about few hours, but I didn't find a way to actually make this URL work.

Previously (before using Zircle UI), I created a routes mapped with `/callback` and mounted a `Callback.vue` component. In `Callback.vue`, I will parse some parameters like `accessToken` ` userId` and store them in vuex, then just simply redirect to a home page whatever.

In Zircle UI routing system, seems like it doesn't support custom URL (I know custom URL sounds stupid XD, but you know what I mean), the URLs using vue-router are like ' http://localhost:8080/home-0'. 

Just like driekus77 explained his idea on routing, I can totally do a mapping between vue-router and Zircle UI routing system, but is there any way to make this happen? I mean in a proper way.

**Comment by tinchox5** [comment]
Hi @phshy0607, thank you for participating in this discussion!

As you said zircle adds a suffix '--n' in the views... The main reason for this is that you can reuse several times the same view. So, to avoid conflicts with previous views zircle differentiates each view from others by adding a suffix. 

Having said that I understand that it would be nice to allow custom urls when you are using vue-router. I mean, if you define routes, those routes should be used and no suffix should be added.

I need some time to rethink the use of vue-router with zircle, since right now it isn't something really useful.

**Comment by tinchox5** [comment]
@phshy0607, @driekus77  I made a little change on zircle to avoid inserting suffix when the router is enabled (v1.2.0). This is a just a small fix. I'll try to find a more comprehensive workaround in some days. Sorry for the inconvenience

**Comment by phshy0607** [comment]
@tinchox5 it's totally fine. Thanks for the contribution! 
I will try it out soon. XD

**Comment by tinchox5** [comment]
**Zircle and vue-router** **WIP**

- [x] Use vue-router **routes** along with **automatic zircle routes** 
```
const router = new Router({
  routes: [
    { path: '/home', name: 'home', component: home },
    { path: '/help', name: 'help', component: docs }
  ]
})

export default {
  components: {
    about: docs
  }
...
```

- [ ] Use routes to render views and set the initial defined view to go back.
Eg: `/documents` will render the document view. When user go back, `/home` will render.

- [ ] Test cases with params, optimize code

**Comment by tinchox5** [comment]
Information and guides on https://zircleui.github.io/docs/guide/using-vue-router.html
