### ISSUE TITLE
z-list pagination indicators show all previous selected

### ISSUE THREAD

**Issue by twhitson** [zircleUI/zircleUI#2]
When moving through pages in a paginated z-list, previous page indicators stay filled in when on any page beyond the first. Reproduced on Firefox Developer Edition 57.0b12 and Chrome 61.0.3163.100.

![Example](https://user-images.githubusercontent.com/4574457/32288215-3afea374-bf01-11e7-9e8d-8382d1f07b10.png)

**Comment by tinchox5** [comment]
Thank you @twhitson, the primary idea was to show a kind of "progression", but I see you point maybe I could add class to show the progression and another to show what page is active, what do you think?

**Comment by tinchox5** [comment]
Hi @twhitson,  the dot navigation style should be fixed in zircle@0.1.5

![Example](https://user-images.githubusercontent.com/11557901/32455079-34b4bd2c-c2ef-11e7-9863-64052429a0de.png)
