### ISSUE TITLE
Blank Canvas on Refresh

### ISSUE THREAD

**Issue by NiharikaPatel** [zircleUI/zircleUI#21]
I'm using Zircle on the mixed mode and the canvas is within a container, However, on refreshing the browser the canvas appears to be the entire viewport and the Zview disappears.

**Comment by tinchox5** [comment]
Hi @NiharikaPatel! Could you provide a codepen to see the issue?

**Comment by tinchox5** [comment]
When you resize the browser's windows the problem persist?

**Comment by NiharikaPatel** [comment]
Hi Juan,

https://jsfiddle.net/37mr5324/50/

This is a little similar to what I am trying to do, however it does not
seem to happen in the JSfiddle result window. I am attaching a video of my
web app to help explain whats happening.
And the problem persists on resizing the browsers window as well.

Thank you,
Niharika

**Comment by tinchox5** [comment]
I couldn't see your video here, maybe you can attach an animated gif on this thread. However, I found a bug related to your issue.  I'll fix tomorrow morning (Canada time).

**Comment by tinchox5** [comment]
Please update zircle to v.1.2.1. There was an error in mixed mode that prevented zircle from taking the size of the container as reference.

**Comment by NiharikaPatel** [comment]
Hi Juan ,

I just updated to zircle v.1.2.1 , However the issue still persists . Was I
supposed to make any changes to the code as well ? I am attaching a GIF
animation of the issue.

Thanks,
Niharika

**Comment by tinchox5** [comment]
You don't have to make any change in your code for this bug fix. There is no attached image... I think you should add it trough Github website.

**Comment by NiharikaPatel** [comment]
Oh I see, So I cannot have a container as a component for the Canvas?

**Comment by tinchox5** [comment]
You should use `z-canvas` as container. You can add an inline style (eg: `style="width: 50%"`) or create a class for `z-canvas`, like:
```
<div id="app">
  <z-canvas :views='$options.components' class="zircle">
  </z-canvas>
</div>
<style>
.zircle {
  width: 50% !important; 
  height:100% !important; 
  border: 2px solid red;
}
</style>
```

If you use a class you need to add `!important` on width and height properties to overrride the initial config.

**Comment by NiharikaPatel** [comment]
I see what you're saying , however We need the zircle to be part of a
component in the main page. I have attached My code below.
The first image is where I define the Z-Canvas (In Canvas.vue) and the
second one is where I call it (FSD.vue). Initially it does take the shape
of the container. However if we route back refresh, It breaks(as seen in
the GIF)

**Comment by tinchox5** [comment]
There is no file attached. You need to drag and drop the image via Github website

**Comment by tinchox5** [comment]
There was not an issue related with zircle

**Comment by NiharikaPatel** [comment]
This issue was not related to Zircle, problem maybe related to the node server.
