### ISSUE TITLE
Zircle css interferes with element UI styling

### ISSUE THREAD

**Issue by NiharikaPatel** [zircleUI/zircleUI#24]
The Zircle.css seems to interfere with the Element UI styling . Some of the widgets get distorted. Is there anyway to restrict the styling to just the Zircle components?

**Comment by tinchox5** [comment]
Sorry to hear that, most of the css classes start with te prefix `z-` to avoid conflicts with other libraries. Could you tell me what classes are causing troubles?

**Comment by NiharikaPatel** [comment]
I am not sure exactly but I am running the Smart home Dashboard example and my canvas is in the mix mode. Everything else is the default setting.

**Comment by tinchox5** [comment]
And what other UI library are you using with?

**Comment by NiharikaPatel** [comment]
Just Element UI.

**Comment by tinchox5** [comment]
I skimmed the Element UI CSS style-sheet and I don't think styles interfere. Mostly, all CSS classes use the prefix `el-` and there aren't exact matches with the Zircle CSS.

**Comment by NiharikaPatel** [comment]
![withzircle](https://user-images.githubusercontent.com/31861212/51936814-e6d4af00-23bd-11e9-9ada-6e58b066f62f.png)
![withoutzircle](https://user-images.githubusercontent.com/31861212/51936824-ec31f980-23bd-11e9-9c5b-900e13bffb12.png)


I have attached two screenshots that show the distortion. The second image shows how its actually supposed to be without the Zircle.css . Apart from the the scrolls tables disappear  and the alignment in breadcrumbs get messed up too.

**Comment by NiharikaPatel** [comment]
Okay, Thank you!

**Comment by tinchox5** [comment]
This bug should be fixed now. In case you want to style input tags with zircle, you can use `.z-input` or create your own class.
Thank you!!

**Comment by NiharikaPatel** [comment]
It still seems broken or my end. I updated my packages too. These are my
current versions of Zircle and Element UI
`"zircle": "^1.3.0"
"element-ui": "^2.4.11",`

**Comment by tinchox5** [comment]
Hi @NiharikaPatel, the zircle version 1.3.0 (is an experimental release). You have to install the latest stable release that is version 1.2.4. Simply, use `npm install zircle`

**Comment by NiharikaPatel** [comment]
Oh I see! Thanks, it works with 1.2.4

**Comment by tinchox5** [comment]
Excellent! Thank you
