### ISSUE TITLE
Newby support request: basic js integration, how to get current time updated?

### ISSUE THREAD

**Issue by zigurana** [zircleUI/zircleUI#25]
Hi enthousiastic but very green newcomer here!
I am attempting to create a home automation interface using Zircle and a Raspberry Pi 3A+.

I've followed the (excellent) documentation and tutorial, quickly stepping over any 'please familiarize yourself with JS and Vue before diving in' - messages :-D.
The tutorial worked out fine, and now I am trying to expand on it.
Because I am using the Pi, I would like to use node packages to talk to the hardware GPIO's, such as `onoff` and `i2c-bus`, so I can connect external sensor modules and buttons, etc.

As a first step towards this, I thought to try and update the Zircle UI from an external source, by using JS native `Date()` method, and piping that through to vue-moment to format the string.
So in my 'home` view, I've added the following:
```
<template>
  <z-view label="zircle demo" label-pos="top" size="xxl">
  <h1>{{ new Date() | moment("HH:MM") }}</h1>
  {{ new Date() | moment("dddd") }} <br>
  {{ new Date() | moment("D MMM YYYY") }}<br>
  <br>
  <h1>{{scene}}</h1>
    <div slot="extension">
      ... all slot definitions
    </div>
   </z-view>
</template>
```
And while this compiles and shows a timestamp  / day of the week / date in the correct format, it never updates! I then tried JS `setInterval()` as an additional script in the home-view to trigger an update, but that had no result. Also the only examples I could find for calling custom methods from Zircle was in situations where a button-press triggered the event: `@click.native="functionCall(arg)"`.

So upon diving into the VueJS documentation, I found out that only variables defined before the instantiation of the Vue object are considered for the reactivity system. So I tried creating a data object with a `getTime()` function in main.js, created before the Vue instance is created, and then feeding it that data, but could not get it to work.
  
The [advanced documentation on reactivity](https://vuejs.org/v2/guide/reactivity.html) goes a bit over my head, though, so now I'm stuck.

Do you have any pointers that might help me out here?

(I understand that this question might be more related to Vue than Zircle, but I think a solution for this might help others trying to get Zircle to work for their applications as well. Once I get this to work, I can contribute the documentation maybe?)

Thanks!

Version info (according to npm):
vue: 2.5.22
zircle: 1.2.4

**Comment by tinchox5** [comment]
Hi @zigurana! Thank you for trying to build a home automation UI with Zircle. Regarding your question, you are right this is something related to Vue. Let me some time to answer properly. Meanwhile, I think this blog could help you: https://cushionapp.com/journal/reactive-time-with-vuejs

**Comment by zigurana** [comment]
Hi, thanks for the response!
I'll dive into that blogpost, to see how far I get.

**Comment by tinchox5** [comment]
@zigurana, I made a little demo of a clock on codepen. The demo is unfinished, but maybe help you to understand how to work with time, zircle and vuejs 

Please check https://codepen.io/zircle/pen/pYjOea

Hope this example helps!


![image](https://user-images.githubusercontent.com/11557901/53583748-2f63c180-3b50-11e9-950a-9591287b4193.png)

**Comment by zigurana** [comment]
Oh wow, that's just great! :+1: 
 
Must be the cutest "minimum functional example" of the month! :1st_place_medal: 

It's also most explanatory, thanks!
