### ISSUE TITLE
Is it possible to know the current view at anytime?

### ISSUE THREAD

**Issue by NiharikaPatel** [zircleUI/zircleUI#27]
Is there anyway to know what the current view is? I want to dynamically display other components based on what the current z-view is.

**Comment by tinchox5** [comment]
Hi @NiharikaPatel! Thank you for filling this issue!

You can use `$zircle.getCurrentViewName()`to find the current view name. Also, it is possible to detect the previous and last view name using `$zircle.getPreviousViewName()` and `$zircle.getPastViewName()`.

I made a very simple example on Codepen to illustrate how to detect the view names:

https://codepen.io/zircle/pen/ROpxgq

![image](https://user-images.githubusercontent.com/11557901/55888036-ab541f00-5b7c-11e9-8f79-6110934b02e8.png)

Hope this help you!

**Comment by tinchox5** [comment]
Also, there is some general information about the "internal API" of Zircle on the documentation that may help you in the future

https://zircleui.github.io/docs/api/internal-api.html
