### ISSUE TITLE
run  sample app can't show home view righ

### ISSUE THREAD

**Issue by samsomlan** [zircleUI/zircleUI#31]
when run  simple dashboard for a smart home app(git clone https://github.com/zircleUI/tutorial.git).

the home view is too large to show. like attach image. why and how to fix it.
![home view too lager to show](https://user-images.githubusercontent.com/5356609/60769175-2c30a180-a0ff-11e9-9141-78280db82771.png)

**Comment by tinchox5** [comment]
Hi @samsomlan, I think that you are running the example with a pre-release version of zircle that is not ready to use. Please try this `npm i zircle@1.2.5`

**Comment by samsomlan** [comment]
after npm i zircle@1.2.5,it work!
