### ISSUE TITLE
Zircle rendering at wrong position on Mobile browser

### ISSUE THREAD

**Issue by Kaissa-Global-Business** [zircleUI/zircleUI#33]
[https://codepen.io/zircle/pen/ejXaNY](https://codepen.io/zircle/pen/ejXaNY)
On Android chrome, four layer down, zircle starts dipping from center of the screen. Same example works perfectly on Web chrome. On web, the zircle dips but renders itself to the center immediately, which is not happening on Android browser. Tested on Android chrome. 

![1](https://user-images.githubusercontent.com/7005124/67844350-98f30000-fb23-11e9-9ed9-45ce6d9de017.jpeg)
![2](https://user-images.githubusercontent.com/7005124/67844351-998b9680-fb23-11e9-91a9-b4a9fc56e1c8.jpeg)
![3](https://user-images.githubusercontent.com/7005124/67844352-998b9680-fb23-11e9-84c9-9ee5dece5d44.jpeg)
![4](https://user-images.githubusercontent.com/7005124/67844353-998b9680-fb23-11e9-95c2-0ccc6300298a.jpeg)

**Comment by tinchox5** [comment]
Thank you for informing this issue. Could you change the zircle version on codepen to zircle@1.4.0-rc.1 or zircle@1.4.0-beta.3 and test again on android?

**Comment by Kaissa-Global-Business** [comment]
### Tested Zircle@1.4.0-beta.3
**Result : Issue is persistent in Android Chrome and even web is affected.**

### Android Chrome
Level 1
![1](https://user-images.githubusercontent.com/7005124/67886211-20199580-fb6f-11e9-869c-75d01df572b5.jpeg)
Level 2
![2](https://user-images.githubusercontent.com/7005124/67886213-20199580-fb6f-11e9-8e8f-0c636ecb7db6.jpeg)
Level 3
![3](https://user-images.githubusercontent.com/7005124/67886216-20199580-fb6f-11e9-9c7e-b45f96d208e8.jpeg)
Level 4
![4](https://user-images.githubusercontent.com/7005124/67886217-20b22c00-fb6f-11e9-9552-5ecfb47f312a.jpeg)
Level 5
![5](https://user-images.githubusercontent.com/7005124/67886218-20b22c00-fb6f-11e9-8dfa-4a7cccccef7f.jpeg)


### Web
Level 1
<img width="622" alt="Screenshot 2019-10-30 at 11 40 30 PM" src="https://user-images.githubusercontent.com/7005124/67886320-4808f900-fb6f-11e9-95bf-71871c0012e4.png">
Level 2
<img width="623" alt="Screenshot 2019-10-30 at 11 40 46 PM" src="https://user-images.githubusercontent.com/7005124/67886319-47706280-fb6f-11e9-9d08-acc7adfc9909.png">
Level 3
<img width="622" alt="Screenshot 2019-10-30 at 11 40 58 PM" src="https://user-images.githubusercontent.com/7005124/67886318-47706280-fb6f-11e9-8ade-0f16997fd080.png">
Level 4
<img width="621" alt="Screenshot 2019-10-30 at 11 41 09 PM" src="https://user-images.githubusercontent.com/7005124/67886316-47706280-fb6f-11e9-9fe8-4546116f1b3d.png">
Level 5
<img width="621" alt="Screenshot 2019-10-30 at 11 41 22 PM" src="https://user-images.githubusercontent.com/7005124/67886315-46d7cc00-fb6f-11e9-902b-b49cd4d64b0a.png">

**Comment by tinchox5** [comment]
Thanks for testing! The issue is a limitation of zircle that occurs when
you zoom deeper. The problem is the scale transform property of the active
view at the fourth of the fifth level has a lot of decimals that are not
handled properly by the browsers. For this reason, the current maximum
level of depth is 5.
To solve that problem I'm drafting a solution to get rid off the limit of
zoom navigation, but I haven't much time to work on it.

**Comment by Kaissa-Global-Business** [comment]
When I did console log of X,Y in position.js for web and mobile

```
X = ((store.actions.getComponentWidth(parentSize) / 2) * distance / 100) * Math.cos(angle * (Math.PI / 180))
Y = ((store.actions.getComponentWidth(parentSize) / 2) * distance / 100) * Math.sin(angle * (Math.PI / 180))
console.log(X,Y)

```    
For the same angle the X,Y are calculated to same decimal precision but they differ in deeper levels. Strange.

In my observation with zircle@stable, on the web the zircle dips down at deeper level but quickly comes back to the center. 
### Which makes me wonder, can the position be manually centered using css. Any suggestions?

**Comment by tinchox5** [comment]
Maybe this can be done by adding a css style with "!important" trying to override the transform property on the current view. However, I believe that to solve this issue it is better to rewrite the position "engine".

**Comment by Kaissa-Global-Business** [comment]
Thanks for the hint. Efforts to manually reset transform failed. When i dug deeper, i found this great article on [browsers rounding up decimal points](https://cruft.io/posts/percentage-calculations-in-ie/)
Turns out that round up of decimal places in transform: translate3d is the culprit and position "engine" isn't at fault.

Zircle's strongest feature is zoom and out which aesthetically depicts hierarchy. If zoom-in and out is just treated as animation and each z-view is rendered with absolute positioning, there's wont be a need to dilute the coordinate system [Background will be lost]. But it's better than enforcing levels on the framework.

Framework's calculation are correct. You may close this thread. Thanks.

**Comment by tinchox5** [comment]
I really appreciate your feedback and interest on zircle. I aware of this
limitations and for this reason I thought in another approach:

Nowadays zircle perfoms true zoom navigation, but as you  know the decimal
points are not well handled by browser. At deeper scales the things behave
weirdly.

So, the objective of the new approach is to ensure the the new view is
rendered always at scale factor 1. But starting  at the same scale of the
previous clicked element. This way you can make zoom indefinitely with out
compromise performance and hierarchical experience. The previous views will
increase the scale factor accordingly and as result the ux will remain
intact

Also, I will split the project in two. One for the circular shapes and the
other for the zoom engine. This way the zoom engine will be used with any
element that has a “is-zoomable” class.

I hope I can deliver soon a working concept.


What do you think?

**Comment by Kaissa-Global-Business** [comment]
Yes, sounds great, as long as transformation aren't in decimal coordinates the problem is solved. **I think your new approach is absolutely correct**.  If the canvas made scaleable, zoom-in is practically infinite. Performance optimisation may be required, since all parents will need to be transformed not just scaled.

**Comment by tinchox5** [comment]
That’s absolutely right! I think writing this solution, the project will be
more stable and less experimental. In this sense, separating the zoom
“engine” from the circle shapes will result in more maintaining and
flexible project.
