### ISSUE TITLE
How to change the speed of the animation between the circles?

### ISSUE THREAD

**Issue by VadimGuslistov** [zircleUI/zircleUI#35]
**What issues can I inform?**
Besides informing a **bug**, you can **propose features, ideas, etc**. 

You can also open an issue if find something in the **documentation** is not clear enough.

**How to inform?**
Just try to explain **what happens** and **what is expected to happen** . Also, it would very useful to provide **a way to reproduce the issue** (JSFiddle, CodePen, CodeSandbox or provide a GitHub repo).

**Comment by tinchox5** [comment]
Hi @VadimGuslistov, 
If you ask regarding how to animate circles as in this example https://zircleui.github.io/docs/examples/vuejs-ecosystem.html, you could try yourself in https://codepen.io/zircle/pen/LeqKGK which is editable.

On line 254 you will see this :
````
:angle="(360 / ecosystem.length * index) + sharedState.ang * 5"
````

To increase the speed you need to alter the number `5` with a large number. For instance,`90`. Try it online to see how the speed is increased.

I hope you refer to something related to my explanation.

**Comment by VadimGuslistov** [comment]
Thanks, but I ask regarding how to increase the speed of the animation circles as in this example:
https://codepen.io/zircle/pen/vqbXvM

**Comment by tinchox5** [comment]
Currently, is not possible to change the speed of the transition. However, in a future version, I would allow users to change the transition speed to fit their needs.
