### ISSUE TITLE
How to resize z-view arbitrarily?

### ISSUE THREAD

**Issue by VadimGuslistov** [zircleUI/zircleUI#36]
**What issues can I inform?**
Besides informing a **bug**, you can **propose features, ideas, etc**. 

You can also open an issue if find something in the **documentation** is not clear enough.

**How to inform?**
Just try to explain **what happens** and **what is expected to happen** . Also, it would very useful to provide **a way to reproduce the issue** (JSFiddle, CodePen, CodeSandbox or provide a GitHub repo).

**Comment by tinchox5** [comment]
Please see this issue https://github.com/zircleUI/zircleUI/issues/29
z-view uses the size xxl. Maybe you can adjust the xxl property. The size is a percentage of the screen. To enable this feature, you need to install `npm install zircle@1.4.0-beta.3
`

**Comment by VadimGuslistov** [comment]
Thanks, but I need to set any size 
ANS 
I use zircle@github-trending-plus, but does it work with zircle@1.4.0-beta.3?

**Comment by tinchox5** [comment]
I think that version should work, but maybe you need to adjust the size properties as is said on #29 
You can't set a fixed size for z-view since it is responsive by design.
