### ISSUE TITLE
How to perform a zoom transition to another view using programmatic navigation?

### ISSUE THREAD

**Issue by VadimGuslistov** [zircleUI/zircleUI#37]
I used programmatic navigation by toView, but a zoom transition to another view does not work. zSpot is just displayed, but there is no effect of zooming it and the surrounding interface.

**Comment by tinchox5** [comment]
Vadim, sorry about that. I’m taking a holiday and I don’t have good
internet access. I’ll be back on February 24th.

**Comment by tinchox5** [comment]
@VadimGuslistov , please see this working codepen with programmatic navigation: https://codepen.io/zircle/pen/yLNgKeP (Pay attention to lines 7-18)

Also I suggest to check the documentation at https://zircleui.github.io/docs/api/z-spot.html#using-programmatic-navigation

Good Luck!!
