### ISSUE TITLE
Using with VueMaterial

### ISSUE THREAD

**Issue by Mashiane** [zircleUI/zircleUI#38]
Im trying this lib out but am getting an error that I cannot solve.

Uncaught TypeError: Cannot read property 'offsetWidth' of null
    at Object.getDimensions (zircle.umd.js:1215)
    at addResizeHandlers (zircle.umd.js:630)

Apparently, the div named z-container cannot be found.

How can I resolve this?

Thanks

**Comment by tinchox5** [comment]
Could you provide a codepen reproducing the issue?
