### ISSUE TITLE
how can i use zircleUI with Vue 3 

### ISSUE THREAD

**Issue by biloo-dev** [zircleUI/zircleUI#44]
i have project with vue 3 and ionic 5 

![dd](https://user-images.githubusercontent.com/37638323/117176594-f2e31e80-adc7-11eb-8d8f-7abcedad02fc.PNG)

how can i fix this error please
 
![image](https://user-images.githubusercontent.com/37638323/117176497-de068b00-adc7-11eb-8caf-bc44a29ceddc.png)

**Comment by tinchox5** [comment]
Hi @biloo-dev sorry for the delay! I'll take a look asap to give you an answer. Nowadays zircle is working for vue 2.x, but I'll try to fix for you

**Comment by biloo-dev** [comment]
Thank you very much @tinchox5 . I will be very grateful to you for your cooperation
I will be waiting for you

**Comment by tinchox5** [comment]
No problem, I have found some guides to adapt 2.xx libraries to 3.x.x. Give some time I'll fix

**Comment by stigmat4j** [comment]
Hi! Any updates?

**Comment by tinchox5** [comment]
Hi! no yet. I’ll do it ASAP. Sorry for the inconveniences.

**Comment by tinchox5** [comment]
Guys, I had Zircle working on Vue 3, but I need to fix many vue warns yet.

**Comment by tinchox5** [comment]
Well, I think zircle is now Vue3 compatible.

Please check Vue3 branch https://github.com/zircleUI/zircleUI/tree/vue3

Also, you can install the package `npm install zircle@vue3`

I worked on the dev branch, so this version of Zircle has some undocumented features. Please see #23

**Comment by tinchox5** [comment]
I forget to mention that when you define your views follow this in order to prevent some Vue warns in console:
````
import { markRaw } from 'vue'
import home from './demo/home.vue'
import docs from './demo/docs.vue'
export default {
  components: {
    home: markRaw(home),
    docs: markRaw(docs)
  }
```

**Comment by tinchox5** [comment]
Caveats: vue router is not ready yet
