### ISSUE TITLE
Problem when using two zircleUI (Vue-electron)

### ISSUE THREAD

**Issue by Ahmed-Sarmoum** [zircleUI/zircleUI#47]
I'm using two zircle in the same project
The problem is that when I open the first and then close it and then open the other, I find the content of the first opens in the second
 
![Capture](https://user-images.githubusercontent.com/58576140/150592016-63c92441-7bf2-4809-8602-e4d771e67133.PNG)
I am using vue-electron

**Comment by tinchox5** [comment]
Sorry Zircle has only one instance. Zumly runs with multiple instances
