### ISSUE TITLE
Nothing is displayed when clicking on z-spot with to-view attribute just after zoom out

### ISSUE THREAD

**Issue by xdidx** [zircleUI/zircleUI#48]
All disappear (big zoom out) when I click on z-spot with to-view attribute just after (less than a second) clicking outside the z-view circle in order to zoom out

I made a video to show it: [*video link*](https://drive.google.com/file/d/1jb9UrMRvWOQsCeIv09bIskLAHdMOyHB5/view)

I tried to add a condition to verify pulse variable, the error wasn't present anymore, but the big zoom out is always present.

This bug is reproductible in all Zircle-UI projects (for example: [https://codesandbox.io/s/23wlzq4l1r](https://codesandbox.io/s/23wlzq4l1r)), on Firefox and Chrome (I haven't tried any other)

**Comment by yearmfew** [comment]
It does not happens on brave browser. I have tried the code in codesandbox.

**Comment by xdidx** [comment]
> It does not happens on brave browser. I have tried the code in codesandbox.

I got the same issue on brave browser [video link](https://drive.google.com/file/d/1r5m4V6-NqDFnDsmC47qpED-xzlePLw6u/view?usp=sharing) :/
