### ISSUE TITLE
Zircle with vue router

### ISSUE THREAD

**Issue by yearmfew** [zircleUI/zircleUI#49]
I am using zircle and another menu in my vue js project in main page. When I click a circle and come back with menu then It appears a zoom back click on the mouse. When I click somewhere in the page, the zircle disappears. 

In documentation I have seen that we should not user vue router and zircle togetger. I am okay with this. But I just need to disable the zoom behaviour of zircle. How can I remove it?

**Comment by tinchox5** [comment]
Hi @yearmfew, please use zircle in mixed mode. https://zircleui.github.io/docs/api/z-canvas.html#full-and-mixed-modes

**Comment by yearmfew** [comment]
Hi. Actually it works in mixed mode. Here is my code. 
Home.vue:
`
<template>
  <div class="home-container">
    <div class="canvas-container">
      <z-canvas :views="$options.components">
        <ReviewCircle> </ReviewCircle>
      </z-canvas>
    </div>
    <div class="reflexionsButton">
      <ReflexionAuswahl :projectId="getProjectID" />
    </div>
  </div>
</template>

<script>
import ReviewCircle from "@/components/ReviewCircle.vue";
import ReflexionAuswahl from "@/components/ReflexionAuswahl.vue";

export default {
  name: "Home",
  components: {
    ReviewCircle,
    ReflexionAuswahl,
  },
  computed: {
    getProjectID() {
      return this.$route.params.project_id;
    },
  },

  mounted() {
    this.$zircle.config({
      mode: "mixed",
      style: {
        theme: "white",
      },
    });
    sessionStorage.setItem("projectId", this.getProjectID);

    this.$store.dispatch("todo/loadToDoFromBackend");
    this.$zircle.setView("ReviewCircle");
    this.$store.dispatch("project/loadCurrentProject");
    this.$store.dispatch(
      "project_phases/loadPhasesFromBackend",
      this.$route.params.project_id
    );
  },
};
</script>
`

ReviewCircle.vue: 

`
<template>
  
  <z-view size="xxl">
    <div class="inside">
      <b> Kollaboratives Literarurreview: </b>
      <br />
      <b> Hildesheimer Ansatz </b>
      <br />
    </div>
    <div slot="extension">
      <z-spot
        v-for="(el, index) in phases"
        button
        size="s"
        :distance="130"
        :angle="el.angle"
        :key="index"
        :image-path="el.image"
        @click.native="goToPhase(index)"
        :id="el.id"
        :class="{ isDone: el.done === true, red: el.done !== true }"
        :label-pos="el.labelPosition"
        v-b-popover.hover.top="el.label"
        zoom: false
      >
        <b-icon :icon="el.iconType" color="white" font-scale="2"></b-icon>
      </z-spot>
    </div>
  </z-view>
</template>

<script>
import { mapGetters } from "vuex";
export default {
  computed: {
    ...mapGetters({
      phases: "project_phases/getPhasesOfProject",
    }),
    getProjectID() {
      return this.$route.params.project_id;
    },
  },
  methods: {
    goToPhase(phase_number) {
      this.$router.push({
        name: "PhaseTemplate",
        params: {
          phase_number: phase_number,
          project_id: this.getProjectID,
        },
      });
    },
    renderMe(ref) {
      this.$zircle.toView({
        to: ref,
        fromSpot: this.$refs[ref],
      });
    },
  },
  
};
</script>
`

**Comment by yearmfew** [comment]
In our project we are using it actually a little bit weird. We are not using the main good functionality "zooming". We are using only the circles as some sort of menu and we just need to click them and go some pages. 
And it is not the main component of our project. It is only one of the pages.
So is there any way to cancel the zoom functionality. I know it is a weird request but it is what we need actually. :)

**Comment by tinchox5** [comment]
I understand, yes I think it could work just as a normal link and without zoomable views. Pls try to remove to-view property and just use a regular href.

**Comment by yearmfew** [comment]
I have removed to-view and made it with normal a href but it still happens. Here is the code

```
 <a  :href="`http://localhost:8081/phasetemplate/${index}/${el.projectId}`" >
    <b-icon :icon="el.iconType" color="white" font-scale="2"></b-icon> 
</a>
```

**Comment by yearmfew** [comment]
When I click a menu item, it works with vue-router. And zircle thinks that I have clicked a circle, I suppose. Even if I make it with normal href, it triggers zoom back because of menu item.

**Comment by yearmfew** [comment]
I am so sorry but it is a huge project. I could not do it on codepen. 
The project is actually is on github. You can check it from here. 
[https://github.com/MethodJules/clr-6]

On develop branch. src/components/reviewCircle in this component I am using zircle. And this component is called from home.vue component in the same directory

**Comment by tinchox5** [comment]
No problem. I was thinking that if you only need a circle shape for your
project, the best think is to use only the css style. Anyway I’ll take a
look

**Comment by xdidx** [comment]
I just read this issue. 
I think it is related to issue #50 (which I created after the current issue).
Maybe this PR could solve your problem too, @yearmfew : https://github.com/zircleUI/zircleUI/pull/55
