### ISSUE TITLE
Data is destroyed while going back to preview views

### ISSUE THREAD

**Issue by guruprasaad123** [zircleUI/zircleUI#5]
I am new to [Zircleui](http://zircleui.github.io/) framework and I have been this framework for my project.And having this weird issue which is changing the behaviour of my app.I have three views , which I have registered in the **main.js** file and here's the code below .
```
import Vue from 'vue'
import Default from './App.vue'
import Search from './search.vue'
import Games from './games.vue'
import Zircle from 'zircle'
import 'zircle/dist/zircle.min.css'
import { log } from 'util';
import Vuex from 'vuex';
import {mapState} from 'vuex';
import store from './store';
Vue.use(Vuex);
Vue.use(Zircle);


new Vue({
  beforeMount () 
  {

    this.$zircleStore.setView('Default');

  },
 computed:mapState(['data'])
 ,
  el: '#app', store,
components:{
Default,
Search, // having problem in this View
Games
}
})
```
# Scenario 1
Default -> Search -> Games <br>
works fine.
# Scenario 2 ( Continuation of Scenario 1 )
Games -> Search
All the data in the Search components are destroyed.
In the Search component the data is available in the **Scenario 1**,
but **Scenario 2**,the data in the Search component is destroyed (which is Weird ,not supposed to happen).
this is what happens while going from **Search** to **Games**,
![capture1](https://user-images.githubusercontent.com/19173193/35719826-061001a8-080d-11e8-8847-3abeefcc7a9b.PNG)
check the data which is disappeared on switching,
Here's my [project](https://bitbucket.org/guru001/cogoport-frontend/src/19fa3ca6428e67a95dbed6a9325958ee5c1034bf/src/?at=master)
![capture2](https://user-images.githubusercontent.com/19173193/35719854-1a50a3c0-080d-11e8-9a2e-6d431cf451ed.PNG)

**Comment by tinchox5** [comment]
Thank for trying Zircle in your project.  I can't access to your source files, could you fork one of this examples and try to reproduce the issue?
https://jsfiddle.net/tinchox5/az5cf0rd/
https://codepen.io/zircle/pen/xpMoRe

**Comment by tinchox5** [comment]
@guruprasaad123 , I tried to reproduce the issue without luck. Here it is the jsfiddle using fake data

https://jsfiddle.net/tinchox5/zLn6m0u0/

**Comment by guruprasaad123** [comment]
you can access this [repo](https://bitbucket.org/guru001/cogoport-frontend) now Please check it out @tinchox5 !

**Comment by tinchox5** [comment]
Oki, I will take a look!

**Comment by tinchox5** [comment]
@guruprasaad123 sorry for the delay, I think I found the issue!
As it is pointed in the jsfiddle of above you need to clone the results (the array you obtained from axios) before to put it in the prop :collection.

your.results.**slice(0)**

```html
    <z-panel view="games" color="green" >
     <z-list
  		slot="circles"
  		**:collection="this.$store.state.data.slice(0)" **
  		:per-page="3">
    	<z-item 
    	slot-scope="props"
    	:item="props.item"
    	:angle="props.angle" 
    	:color="'purple'" 
    	:label="props.item.title"
    	:image="gamelogo"> 
    	</z-item>
    </z-list>
    </z-panel>
</template>
```
You can clone the results inside the vue instance `data()`

Hope that helps you !

Thank you for open the issue!

**Comment by tinchox5** [comment]
As far as I know this is not properly a Zircle's bug, but a normal situation triggers a mutation of an array. For this reason is that you have to work with a "copy" of the results.  I'm not an expert using axios or working with Vuex, maybe thare some options to create copies of the results without mutate the original ones.

That is what I did it in the jsfiddle.
...
const games = {
  name: 'games',
  template: `<z-panel view="games">
  <z-list
    slot="circles"
    :collection="myresults"
    :per-page="3">
      <z-item slot-scope="props"
      :item="props.item" 
      :angle="props.angle"
      :label="props.item"  			    		image="https://zircleui.github.io/zircleUI/examples/imageslider/one.jpg"
      >
      </z-item>
  </z-list>
</z-panel>`,
  data () {
    return {
      sharedState: store.state
    }
  },
  computed: {
    myresults () {
      // clone array before put en collection prop
      ***return this.sharedState.results.slice(0)***
    }
  }
....
}

**Comment by guruprasaad123** [comment]
you can access this [repo](https://bitbucket.org/guru001/cogoport-frontend) now Please check it out @tinchox5 !

**Comment by tinchox5** [comment]
Yes, I ve already access and I found your problem as I wrote above.

**Comment by guruprasaad123** [comment]
Yes, seems like your hack does works...but I can't really understand how ?. Hope you provide an explanation on how / why the data is deployed while switching to previous states @tinchox5
