### ISSUE TITLE
a problem when using two zircle into a deferent component with different functionality 

### ISSUE THREAD

**Issue by Ahmed-Sarmoum** [zircleUI/zircleUI#51]
The components overlap when the zircleis opened

first zircle
![v1](https://user-images.githubusercontent.com/58576140/176183000-bbf967d1-ffdb-42b9-bda1-ca41f4626da2.PNG)

second zircle
![v2](https://user-images.githubusercontent.com/58576140/176183067-392376f1-37a4-461b-bd40-802de1ab1e79.PNG)

the problem (The overlap between them)
![v3](https://user-images.githubusercontent.com/58576140/176183317-96dc500b-b9ed-4536-bca2-5363cb19477f.PNG)

**Comment by tinchox5** [comment]
Hi @Ahmed-Sarmoum as you asked in #47 the problem is that zircle only has one instance. You can't use more than one zircle on the same app. Zumly on the other hand, accepts multiple instances

**Comment by Ahmed-Sarmoum** [comment]
@tinchox5  thank you bro
